In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5613, 8042, 2619, 2811],
 [5613, 8042, 2619, 1797],
 [5613, 1493, 2619, 4519],
 [6835, 8612, 5901, 844, 7532],
 [6835, 8612, 5901, 844, 3305],
 [9591, 5613, 1511, 2619, 9903],
 [2669, 3563, 2788, 844]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5613 8042 2619 2811]
 [   0    0    0    0 5613 8042 2619 1797]
 [   0    0    0    0 5613 1493 2619 4519]
 [   0    0    0 6835 8612 5901  844 7532]
 [   0    0    0 6835 8612 5901  844 3305]
 [   0    0    0 9591 5613 1511 2619 9903]
 [   0    0    0    0 2669 3563 2788  844]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\GenAI_udemy\simple_rnn_imdb\venv_RNN\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step


array([[[-0.04794334, -0.02215635, -0.00122076, -0.02461982,
          0.02970224,  0.03698659,  0.04334093,  0.00023353,
         -0.04153144, -0.02661128],
        [-0.04794334, -0.02215635, -0.00122076, -0.02461982,
          0.02970224,  0.03698659,  0.04334093,  0.00023353,
         -0.04153144, -0.02661128],
        [-0.04794334, -0.02215635, -0.00122076, -0.02461982,
          0.02970224,  0.03698659,  0.04334093,  0.00023353,
         -0.04153144, -0.02661128],
        [-0.04794334, -0.02215635, -0.00122076, -0.02461982,
          0.02970224,  0.03698659,  0.04334093,  0.00023353,
         -0.04153144, -0.02661128],
        [-0.04941895, -0.00385017,  0.04181052,  0.02468984,
         -0.0344377 ,  0.04264349, -0.04046105,  0.04912448,
         -0.0278409 , -0.04676274],
        [-0.02666429,  0.03335946,  0.02759898, -0.01572172,
          0.04573517,  0.04177583,  0.01563381,  0.02062497,
          0.00597432,  0.00659958],
        [ 0.03028547, -0.02763261, -0.03745228, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 5613, 8042, 2619, 2811])

In [18]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None